### ISSUE TITLE
action-preconditions hard enforcement

### ISSUE THREAD

**Issue by ataitler** [ataitler/pyRDDLGym#100]
Currently action-preconditions are not enforced and present in the RDDL only for model-based planning usage.
A boolean flag for the environment should be added to specify the user desire to enforce the action-preconditions in case ho choses so. There might be users who might what this functionality.

**Comment by mike-gimelfarb** [comment]
agreed. We can follow the jax compiler approach where the flag determines if the constraints are hard or soft enforced (eg warning vs exception). This also allows for a silent mode if the user wishes.

**Comment by ataitler** [comment]
Exactly what I was thinking, hard, soft and silent. where the default is silent I think.
