### ISSUE TITLE
 Better handling of undefined variables potentially initialized in the domain instance.

### ISSUE THREAD

**Issue by mike-gimelfarb** [ataitler/pyRDDLGym#103]
Currently it seems no warning or error is raised in such cases? We may want to investigate this in the next updates.

**Comment by ataitler** [comment]
We should add a check during grounding to make sure it does not happen. In the UAV example we should have raised "MIN-VEL does not exists in UAV domain"

**Comment by mike-gimelfarb** [comment]
This has been fixed with the recent commit. Now we discover there are a few domains that have invalid non-fluents or init-state declarations. Should we leave them as is for the purposes of the competition, or fix them?

**Comment by ssanner** [comment]
> that have invalid non-fluents or init-state declarations. Should we leave
them as is for the purposes of the competition, or fix them?

Please fix these bugs when you have time.  These are not final competition
domains/instances (they are TBD), but we definitely don't want bugs in the
repo examples in general.

Thanks,
Scott

**Comment by mike-gimelfarb** [comment]
Fixed.

**Comment by mike-gimelfarb** [comment]
I am closing this issue. Feel free to reopen if I missed something.
