### ISSUE TITLE
Additional features 

### ISSUE THREAD

**Issue by mike-gimelfarb** [ataitler/pyRDDLGym#104]
There are a couple things that I’d say might still be worthwhile to implement because they give flexibility at potentially little development cost:

1. Support for categorical distribution - if I recall we don’t have this because it requires enum. However we could hypothetically implement this without enum through the use of pvariable like so

sample = Categorical[p] where p is a parameterized real type eg p(?atom)

this is just syntactic sugar for something that could be done via Bernoulli but will be quite hard to specify.

2. Support for state action constraints - we talked about this but I think there could be cases where we want constraints to be function of both state and action. Currently doing this with either invariant or precondition will trigger a crash. It wouldn’t be supported by the gym most likely so perhaps this is not as important for the time being.

What do you think?

**Comment by ssanner** [comment]
Hi Mike,

1. I'd ask people to hold off on changes to the RDDL language (keep in mind
that various people have used and still use Java RDDL) until we discuss
them and decide these are changes we need for all of eternity (errr, maybe
a decade).

2. We don't need state-action-constraints at all:
- action-preconditions can absolutely be a function of state -- this is the
point of action preconditions that determine which joint action assignments
are legal in which states.  I'm not sure why we currently disallow
action-preconditions as a function of state?  I'm fine if the default is to
ignore them for purposes of Gym, but we should at least have a
configuration flag that supports their original intent (i.e., the simulator
terminates if the agent selects an illegal action in a state).
- state-invariants should never be a function of actions... they are like
C-style assertions of state properties (only) that should never be violated
by legal transitions taken from a legal initial state (e.g., an elevator at
two places at the same time).

Cheers,
Scott

**Comment by mike-gimelfarb** [comment]
Hi Scott,

1. understood. we could also just implement enum as the original language intended.
2. I think the discussion was for gym environments, we could not enforce action constraints that are state dependent, as there is no way to encode it in gym from my understanding. in this case, i will need to check that they are still allowed to be state dependent outside gym environments.

**Comment by mike-gimelfarb** [comment]
Ok, so unfortunately I hard coded that action precondition does not depend on the state. This is an easy fix though.

**Comment by mike-gimelfarb** [comment]
This has been addressed now that the new language changes are in main.
Closing.
