### ISSUE TITLE
Does aggregation support enum types?

### ISSUE THREAD

**Issue by mike-gimelfarb** [ataitler/pyRDDLGym#144]
Does RDDL support aggregations such as sum_{?q : enum_values} [ do something with ?q ]? What is a typical use case for this?
Currently there is a design choice to be made whether enum types should be handled the same as objects. Currently there are two separate dictionaries for storing enum vs objects, and only the object dict is checked for valid type during simulation.

**Comment by mike-gimelfarb** [comment]
Ok yes it does. If I recall correctly we had a discussion that enum and object types can often be used interchangeable. There are domains in IPPC 2018 I see that did just that. Adding it now.

**Comment by ssanner** [comment]
Please see my shared Google document that we went over... there should be
no distinction between enums and objects.

Thanks,
Scott

**Comment by mike-gimelfarb** [comment]
This is now fixed in the latest commits. Support is also added for literal evaluation in pvariables, and an example from IPPC 2018 is now working.
