### ISSUE TITLE
Release 1.0.0 on PyPI potentially missing files

### ISSUE THREAD

**Issue by pecey** [ataitler/pyRDDLGym#148]
I was trying out pyRDDL Gym and installed it using pip. I tried to run the example code using README, but got an error while importing the package.
![image](https://user-images.githubusercontent.com/11463842/215198533-7eb9874a-b6b1-48ff-9b83-45c5820d833d.png)

I verified the source files by downloading version 1.0.0 and 0.99.0 that while 0.99.0 contains a Debug folder inside Core, 1.0.0 doesn't, but it is being referenced to. Surprisingly, the folder exists in Github. 

Can this be fixed on PyPI? Please let me know if I am missing something or you would like any more information.

**Comment by ataitler** [comment]
Hi! Thanks for bringing it to our attention.
Indeed we missed a file during packaging.
Version 1.0.1 has been uploaded to PyPI, and everything seems to be working correctly now.
However, please let us know if you encounter any additional problems and we will do our best to fix them ASAP.
