### ISSUE TITLE
Run error for the demo code on the tutorials

### ISSUE THREAD

**Issue by Zhennan-Wu** [ataitler/pyRDDLGym#153]
I was trying to run the demo code but ran into the following error:

    agent = RandomAgent(action_space=myEnv.action_space, num_actions=myEnv.NumConcurrentActions)
AttributeError: 'RDDLEnv' object has no attribute 'NumConcurrentActions'

Could someone provide some help?

I am attaching the demo code below for reference.

from pyRDDLGym import RDDLEnv
from pyRDDLGym import ExampleManager
from pyRDDLGym.Policies.Agents import RandomAgent

ENV = 'Wildfire'

# get the environment infos
EnvInfo = ExampleManager.GetEnvInfo(ENV)

# set up the environment class, choose instance 0 because every example has at least one example instance
myEnv = RDDLEnv.RDDLEnv(domain=EnvInfo.get_domain(), instance=EnvInfo.get_instance(0))
# set up the environment visualizer
myEnv.set_visualizer(EnvInfo.get_visualizer())
# set up an example aget
agent = RandomAgent(action_space=myEnv.action_space, num_actions=myEnv.NumConcurrentActions)

total_reward = 0
state = myEnv.reset()

for step in range(myEnv.horizon):
    myEnv.render()
    action = agent.sample_action()
    next_state, reward, done, info = myEnv.step(action)
    total_reward += reward
    state = next_state
    if done:
        break

print("episode ended with reward {}".format(total_reward))
myEnv.close()

**Comment by ataitler** [comment]
Hi,
Thanks for bringing that to our attention.
There is indeed a typo in the example code, It has been fixed one.

The property should be numConcurrentActions.

**Comment by ataitler** [comment]
Tutorial is now fixed.
