### ISSUE TITLE
Reservoir viz references invalid fluent

### ISSUE THREAD

**Issue by mike-gimelfarb** [ataitler/pyRDDLGym#163]
The reservoir viz references an object "res" that does not exist, instead of "id". I believe there is a corrected reservoir domain we discussed on another branch, so perhaps we should merge it into main?

**Comment by ataitler** [comment]
The reservoir domain has been replaced with two version, so the old one will be completely removed.
There is a new visualizer as well.

Update soon.

**Comment by ataitler** [comment]
The reservoir control problem has been updated with appropriate viz.
